name: Run Workflow Based On Changed Paths

on:
  workflow_call:
    outputs:
      proceed:
        description: "Determines if the workflow should proceed based on modified paths."
        value: ${{ jobs.non_md_changes.outputs.non_markdown_changes }}

jobs:
  non_md_changes:
    runs-on: ubuntu-latest
    if: github.actor != 'restyled-io[bot]'
    outputs:
      non_markdown_changes: ${{ steps.filter.outputs.non_markdown_changes }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for non-markdown files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            non_markdown_changes:
              - '!**/*.md'